x-api: &api
  image: rinha-2026-local
  platform: linux/amd64
  command: ["/usr/local/bin/fraud_api"]
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    RINHA_INDEX_PATH: /opt/rinha/index.bin
    API_SOCKET_PATH: /run/rinha/api.sock
    RINHA_INDEX_PROFILE: ${RINHA_INDEX_PROFILE:-}
    RINHA_INDEX_PROFILE_EVERY: ${RINHA_INDEX_PROFILE_EVERY:-}
  security_opt:
    - seccomp=unconfined
  
  deploy:
    resources:
      limits:
        cpus: "0.45"
        memory: "150MB"
        # cpus: "0.30"
        # memory: "100MB"
  volumes:
    - rinha-sockets:/run/rinha
  networks:
    - rinha

services:
  lb:
    build:
      context: .
      dockerfile: Dockerfile
    image: rinha-2026-local
    platform: linux/amd64
    command: ["/usr/local/bin/fraud_lb"]
    environment:
      BACKENDS: unix:/run/rinha/api1.sock,unix:/run/rinha/api2.sock
      # BACKENDS: unix:/run/rinha/api1.sock,unix:/run/rinha/api2.sock,unix:/run/rinha/api3.sock
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
      # - api3
    security_opt:
      - seccomp=unconfined
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "50MB"
    volumes:
      - rinha-sockets:/run/rinha
    networks:
      - rinha
    cpuset: "0,2"

  api1:
    <<: *api
    environment:
      RINHA_INDEX_PATH: /opt/rinha/index.bin
      API_SOCKET_PATH: /run/rinha/api1.sock
      RINHA_INDEX_PROFILE: ${RINHA_INDEX_PROFILE:-}
      RINHA_INDEX_PROFILE_EVERY: ${RINHA_INDEX_PROFILE_EVERY:-}
    cpuset: "0,1"

  api2:
    <<: *api
    environment:
      RINHA_INDEX_PATH: /opt/rinha/index.bin
      API_SOCKET_PATH: /run/rinha/api2.sock
      RINHA_INDEX_PROFILE: ${RINHA_INDEX_PROFILE:-}
      RINHA_INDEX_PROFILE_EVERY: ${RINHA_INDEX_PROFILE_EVERY:-}
    cpuset: "2,3"
  # api3:
  #   <<: *api
  #   environment:
  #     RINHA_INDEX_PATH: /opt/rinha/index.bin
  #     API_SOCKET_PATH: /run/rinha/api3.sock
  #     RINHA_INDEX_PROFILE: ${RINHA_INDEX_PROFILE:-}
  #     RINHA_INDEX_PROFILE_EVERY: ${RINHA_INDEX_PROFILE_EVERY:-}

volumes:
  rinha-sockets:

networks:
  rinha:
    driver: bridge
